COMANDOS = {
    "CPE-HQ": [
        "conf terminal",
        "no crypto isakmp key TLN03 address 190.0.0.1",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-BRANCH",
        "no crypto ipsec transform-set TS-TO-BRANCH",
	    "crypto isakmp key TLN03 address 0.0.0.0",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",

        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",

        "interface Tunnel1",
        "ip address 172.16.10.1 255.255.255.0",
        "no ip redirects",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp map multicast dynamic",
        "ip nhrp redirect",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN",
        "tunnel key 100",
        "ip ospf priority 255",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
	    "ip ospf network broadcast",
        "exit",
        "router ospf 10",
        "no network 172.16.10.0 0.0.0.3 area 0",
        "network 172.16.10.0 0.0.0.255 area 0",
        "exit",
        "end",
    ],

    "CPE-HQ-BK": [
        "conf terminal",
        "no crypto isakmp key TLN03 address 200.0.1.1",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-BRANCH",
        "no crypto ipsec transform-set TS-TO-BRANCH",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",

        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",

        "interface Tunnel1",
        "ip address 172.16.10.100 255.255.255.0",
        "no ip redirects",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp map multicast dynamic",
        "ip nhrp redirect",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN",
	    "tunnel key 100",
        "ip ospf priority 254",
        "ip ospf cost 100",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "exit",
        "router ospf 10",
        "no network 172.16.20.0 0.0.0.3 area 0",
        "network 172.16.10.0 0.0.0.255 area 0",
        "exit",
        "end",
    ],    

    "CPE-BRANCH": [
        "conf terminal",
        "no crypto isakmp key TLN03 address 200.0.0.1",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-HQ",
        "no crypto ipsec transform-set TS-TO-HQ",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",
        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",
        "interface Tunnel1",
        "ip address 172.16.10.2 255.255.255.0",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.10.1 nbma 200.0.0.1 multicast",
        "ip nhrp nhs 172.16.10.100 nbma 190.0.1.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "tunnel key 100",
        "ip ospf cost 10",
        "ip ospf priority 0",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "exit",
        "router ospf 10",
        "no network 172.16.10.0 0.0.0.3 area 0",
        "network 172.16.10.0 0.0.0.255 area 0",
        "exit",
        "end",
    ],
    "CPE-BRANCH2": [
        "conf terminal",
        # Crypto - sin hash md5 ni group 5 que fallan en esta version IOS
        "crypto isakmp policy 10",
        "encr aes",
        "authentication pre-share",
        "group 14",
        "lifetime 1000",
        "exit",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",
        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",
        # Interfaces
        "interface Loopback0",
        "ip address 180.0.0.1 255.255.255.255",
        "exit",
        "interface Ethernet0/1",
        "ip address 10.0.0.73 255.255.255.252",
        "ip nat outside",
        "no shutdown",
        "exit",
        "interface Ethernet0/2",
        "no ip address",
        "no shutdown",
        "exit",
        "interface Ethernet0/2.25",
        "encapsulation dot1Q 25",
        "ip address 192.168.25.2 255.255.255.0",
        "ip nat inside",
        "vrrp 25 ip 192.168.25.1",
        "vrrp 25 priority 110",
        "vrrp 25 preempt",
        "exit",
        # Tunnels
        "interface Tunnel1",
        "ip address 172.16.10.4 255.255.255.0",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.10.1 nbma 200.0.0.1 multicast",
        "ip nhrp nhs 172.16.10.100 nbma 190.0.1.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "tunnel key 100",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "ip ospf priority 0",
        "exit",
        "router ospf 10",
        "router-id 5.5.5.5",
        "network 172.16.10.0 0.0.0.255 area 0",
        "network 192.168.25.0 0.0.0.255 area 0",
        "passive-interface Ethernet0/2.25",
        "exit",
        # NAT y rutas
        "ip route 0.0.0.0 0.0.0.0 10.0.0.74",
        "ip access-list standard 10",
        "10 permit 192.168.25.0 0.0.0.255",
        "exit",
        "ip nat pool BRANCH2-POOL 180.0.0.2 180.0.0.6 prefix-length 29",
        "ip nat inside source list 10 pool BRANCH2-POOL overload",
        "end",
    ],

    "M3": [
        "conf terminal",
        "interface Ethernet1/0",
        "ip address 10.0.0.74 255.255.255.252",
        "ip ospf network point-to-point",
        "no shutdown",
        "exit",
        "router ospf 10",
        "network 10.0.0.72 0.0.0.3 area 0",
        "exit",
        # Ruta estatica - M3 usa redistribute static sin tag
        "ip route 180.0.0.0 255.255.255.248 10.0.0.73",
        "end",
    ],

    "SW2-R-PISO1": [
        "conf terminal",
        "vlan 25",
        "name VLAN25",
        "exit",
        "interface ethernet0/1",
        "switchport trunk encapsulation dot1q",
        "switchport mode trunk",
        "switchport trunk allowed vlan 25",
        "exit"
        "interface ethernet0/2",
        "switchport trunk encapsulation dot1q",
        "switchport mode trunk",
        "switchport trunk allowed vlan 25",
        "exit",
        "interface ethernet0/3",
        "switchport mode access",
        "switchport access vlan 25",
        "exit",
        "interface ethernet1/0",
        "switchport mode access",
        "switchport access vlan 25",
        "exit"
    ]

}